#pragma once

#define WINDY_AGILITY_NOT_IMPLEMENTED() static_assert(false, "NOT IMPLEMENTED!")

#define WINDY_AGILITY_NOT_FINISHED()

#define WINDY_AGILITY_SEGMENT_BEGIN()

#define WINDY_AGILITY_SEGMENT_END()

#define WINDY_AGILITY_FUTURE_REFACTOR()

#define WINDY_AGILITY_FUTURE_OPTIMIZATION()